apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-springboot-properties-2.2
data:
  MANAGEMENT_ENDPOINTS_ENABLED-BY-DEFAULT: 'true'
  MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_EXCLUDE: shutdown
  MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE: '*'
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE: shutdown
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
  MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS: ALWAYS
  MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED: 'false'
  MANAGEMENT_METRICS_ENABLE_ALL: 'true'
  MANAGEMENT_METRICS_TAGS_APPLICATION: '${spring.application.name}'
  MANAGEMENT_SERVER_PORT: '8081'
  SERVER_PORT: '8080'
  SERVER_TOMCAT_ACCESSLOG_BUFFERED: 'false'
  SERVER_TOMCAT_ACCESSLOG_DIRECTORY: /ac/var/jakarta/logs
  SERVER_TOMCAT_ACCESSLOG_ENABLED: 'true'
  SERVER_TOMCAT_ACCESSLOG_MAX-DAYS: '2'
  SERVER_TOMCAT_ACCESSLOG_PREFIX: access
  SERVER_TOMCAT_ACCESSLOG_ROTATE: 'true'
  SERVER_TOMCAT_ACCESSLOG_SUFFIX: .log
  SERVER_TOMCAT_URI-ENCODING: utf-8
  LOGGING_FILE_NAME: '/ac/var/jakarta/logs/catalina.out'
  LOGGING_FILE_MAXHISTORY: '14'
  LOGGING_FILE_MAXSIZE: '10MB'
  # SERVER_TOMCAT_ACCESSLOG_PATTERN: >-
  #   {"DateTime":"%{yyyy-MM-dd'T'HH:mm:ss.SSSZZ}t",
  #   "RemoteIP":"%a","Method":"%m", "URI":"%U", "RequestProtocol":"%H",
  #   "ResponseCode":%s, "ResponseTime":%D,
  #   "X-Forwarded-For":"%{X-Forwarded-For}i", "X-Real-IP":"%{x-real-ip}i",
  #   "X-Auth-User":"%{x-auth-user}i", "AC-TraceId":"%{x-b3-traceid}i",
  #   "AC-Id":"%{x-b3-spanid}i", "AC-ParentId":"%{x-b3-parentspanid}i",
  #   "AC-ServiceName":"${spring.application.name}",
  #   "AC-Version":"${info.version}"}