apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "spring-boot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-boot.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8  }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SW_AGENT_NAME
              value: "{{ .Release.Name }}"
          {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          envFrom:
          {{- if .Values.envFrom }}
          # envForm
          {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
#          {{- if .Values.sidecar.enabled }} {{- if .Values.sidecar.envFrom }}
#          # sidecar envForm
#          {{- toYaml .Values.sidecar.envFrom | nindent 12 }}
#          {{- end }} {{- end }}
          ports:
          {{- if .Values.ports }}
          {{- toYaml .Values.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.mount.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.mount.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.sidecar.enabled }}
      - name: {{ .Release.Name }}-sidecar
        image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
        imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
        ports:
        {{- if .Values.sidecar.ports }}
        {{- toYaml .Values.sidecar.ports | nindent 12 }}
        {{- end }}
        env:
          - name: AC-NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        {{- if .Values.sidecar.env }}
        {{- toYaml .Values.sidecar.env | nindent 12 }}
        {{- end }}
        {{- if .Values.sidecar.envFrom }}
        envFrom:
          {{- toYaml .Values.sidecar.envFrom | nindent 12 }}
        {{- end }}
        resources:
        {{- if .Values.sidecar.resources }}
        resources:
          {{- toYaml .Values.sidecar.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.sidecar.mount.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.sidecar.mount.volumeMounts | nindent 12 }}
        {{- end }}
      {{- end }}
      volumes:
      # volume
      {{- if .Values.mount.volumes }}
      {{- toYaml .Values.mount.volumes | nindent 8 }}
      {{- end }}
      # sidecar volume
      {{- if .Values.sidecar.enabled }} {{- if .Values.sidecar.mount.volumes }}
      {{- toYaml .Values.sidecar.mount.volumes | nindent 8 }}
      {{- end }} {{- end }}
      # nodeSelector
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

