{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
  annotations:
    {{- if .tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - pathType: Prefix
          path: {{ .Values.ingress.path }}
          backend:
            service:
              name: {{ default .Release.Name .Values.ingress.service }}
              port:
                number: {{ .Values.ingress.port }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
        - pathType: Prefix
          path: {{ default "/" .path }}
          backend:
            service:
              name: {{ default .Release.Name .Values.ingress.service }}
              port:
                number: {{ .Values.ingress.port }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: 
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}